require('nvim-treesitter.configs').setup {
    ensure_installed = {
        "c",
        "cmake",
        "cpp",
        "css",
        "dockerfile",
        "fish",
        "gitignore",
        "go",
        "gomod",
        "html",
        "java",
        "javascript",
        "json",
        "latex",
        "llvm",
        "lua",
        "make",
        "markdown",
        "nix",
        "regex",
        "rust",
        "scss",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "verilog",
        "vim",
        "vue",
        "yaml",
    },
    auto_install = true,
    highlight = {
        enable = true,
        additional_vim_regex_highligting = true,
    },
    indent = { enable = true }
}
